services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    ports:
      - "8849:8848"
    environment:
      - MODE=standalone
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    networks:
      - readingapp-network

  db:
    build: ./mysql
    container_name: readingapp-db
    restart: always
    environment:
      MYSQL_DATABASE: vue_reading_app
      MYSQL_ROOT_PASSWORD: "13603994106"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - readingapp-network

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    command: ["java", "-jar", "gateway-service.jar"]
    environment:
      - NACOS_SERVER=nacos:8848
    depends_on:
      - nacos
      - db
    networks:
      - readingapp-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    command: ["java", "-jar", "auth-service.jar"]
    environment:
      - NACOS_SERVER=nacos:8848
    depends_on:
      - nacos
      - db
    networks:
      - readingapp-network

  document-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document-service
    command: ["java", "-jar", "document-service.jar"]
    environment:
      - NACOS_SERVER=nacos:8848
    depends_on:
      - nacos
      - db
    networks:
      - readingapp-network

  study-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-service
    command: ["java", "-jar", "study-service.jar"]
    environment:
      - NACOS_SERVER=nacos:8848
    depends_on:
      - nacos
      - db
    networks:
      - readingapp-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    command: ["java", "-jar", "user-service.jar"]
    environment:
      - NACOS_SERVER=nacos:8848
    depends_on:
      - nacos
      - db
    networks:
      - readingapp-network

  frontend:
    build:
      context: ./frontend
    container_name: readingapp-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - gateway-service
    networks:
      - readingapp-network

networks:
  readingapp-network:
    driver: bridge

volumes:
  db_data: